dnaStrings/urls.py
from django.conf.urls import url
from dnaStrings import views

app_name = "dnaStrings"

urlpatterns = [
    url(r"^submit/$", views.dnaStringsView, name="submit"),
    url(r"^monitor/$", views.monitor, name="monitor"),
    url(r"^delete_job/(?P<task_id>.+)/$", views.delete_job, name="delete_job"),
    url(r"^cancel_job/(?P<task_id>.+)/$", views.cancel_job, name="cancel_job"),
]

gnkg/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from dnaStrings import views

urlpatterns = [
    url(r"^gnkg/", include("dnaStrings.urls")),
    url(r"^submit/$", views.dnaStringsView, name="submit"),
    url(r"^admin/", admin.site.urls),
]

dnaStrings/models.py
from django.db import models


# Create your models here.
class Tasks(models.Model):
    task_id = models.CharField(max_length=200) # generated by celery so random
    job_name = models.CharField(max_length=200) # user input
    dna_string = models.TextField(max_length=1000) # user input
    dna_result = models.TextField(max_length=2000) # result of find_protein function

    def __str__(self):
        return f"{self.task_id} {self.job_name}"

dnaStrings/forms.py
from django import forms


class dnaStringSubmission(forms.Form):
    job_name = forms.CharField(label="Job Title")
    dna_string = forms.CharField(
        label="DNA Sequence", widget=forms.Textarea, max_length=1000
    )

dnaStrings/views.py
from celery.result import AsyncResult
from django.shortcuts import render
from django.views.decorators.http import require_GET, require_http_methods

from dnaStrings.forms import dnaStringSubmission
from dnaStrings.models import Tasks
from dnaStrings.tasks import findProtein
from django.contrib import messages


@require_http_methods(["GET", "POST"])
def dnaStringsView(request):
    if request.method == "POST":
        form = dnaStringSubmission(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            job_name = data["job_name"]
            dna_string = data["dna_string"]

            # send it to the celery worker (delay method)
            findProtein.delay(job_name=job_name, dna_string=dna_string)
            # generate a success method
            messages.success(
                request,
                f"Your job {job_name} was submitted. Click Monitor Jobs to see its progress.",
            )
            # return the same form back to user to enter more data
            return render(request, "submit.html", context={"form": dnaStringSubmission})
    else:
        return render(request, "submit.html", context={"form": dnaStringSubmission})

# polling function
def track_jobs():
    entries = Tasks.objects.all()
    information = []
    for item in entries:
        progress = 100  # max value for bootstrap progress bar, when  the job is finished
        result = AsyncResult(item.task_id)
        if isinstance(result.info, dict):
            progress = result.info["progress"]
        information.append(
            [item.job_name, item.dna_string, item.dna_result, result.state, progress, item.task_id]
        ) # could possibly be used dynamically
    return information


# monitor view
@require_GET
def monitor(request):
    info = track_jobs()
    return render(request, "monitor.html", context={"info": info})


# cancel completely cancels the task from the queue and stops evaluating it
@require_GET
def cancel_job(request, task_id=None):
    result = AsyncResult(task_id)
    result.revoke(terminate=True)
    info = track_jobs()
    return render(request, "monitor.html", context={"info": info})

# deletes the job from the database
@require_GET
def delete_job(request, task_id=None):
    a = Tasks.objects.filter(task_id=task_id)
    a.delete()
    info = track_jobs()
    return render(request, "monitor.html", context={"info": info})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="Ginkgo Coding Challenge" content="">
    <meta name="Shaurya Chanana" content="">
    {% block meta %}
    
    {% endblock meta %}

    <title>{% block title %}
        {% endblock title %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="{% static 'dnaStrings/monitor.css' %}" rel="stylesheet">

    <!-- Favicon Error Fix (add a favicon) https://stackoverflow.com/a/57261359 -->
    <link rel="shortcut icon" href="{% static 'dnaStrings/favicon.ico' %}">

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="#">Ginkgo Coding Challenge</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'dnaStrings:monitor' %}">Monitor Jobs
                            <span class="sr-only"></span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'dnaStrings:submit' %}">Submit More Jobs
                            <span class="sr-only"></span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-12">

                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}

                {% block content %}

                {% endblock content %}



                <!-- Pagination -->
                <!-- <ul class="pagination justify-content-center mb-4">
                    <li class="page-item">
                        <a class="page-link" href="#">&larr; Older</a>
                    </li>
                    <li class="page-item disabled">
                        <a class="page-link" href="#">Newer &rarr;</a>
                    </li>
                </ul>

            </div> -->

                <!-- Sidebar Widgets Column -->
                <!-- <div class="col-md-4"> -->

                <!-- Search Widget -->
                <!-- <div class="card my-4">
          <h5 class="card-header">Search</h5>
          <div class="card-body">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-append">
                <button class="btn btn-secondary" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div> -->

                <!-- Categories Widget -->
                <!-- <div class="card my-4">
          <h5 class="card-header">Categories</h5>
          <div class="card-body">
            <div class="row">
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">Web Design</a>
                  </li>
                  <li>
                    <a href="#">HTML</a>
                  </li>
                  <li>
                    <a href="#">Freebies</a>
                  </li>
                </ul>
              </div>
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">JavaScript</a>
                  </li>
                  <li>
                    <a href="#">CSS</a>
                  </li>
                  <li>
                    <a href="#">Tutorials</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div> -->

                <!-- Side Widget -->
                <!-- <div class="card my-4">
          <h5 class="card-header">Side Widget</h5>
          <div class="card-body">
            You can put anything you want inside of these side widgets. They are easy to use, and feature the new
            Bootstrap 4 card containers!
          </div>
        </div> -->

            </div>

        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Shaurya Chanana 2020</p>
        </div>
        <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

</body>

</html>

templates/monitor.html
{% extends 'base.html' %}

{% block meta %}
{% comment %} page refresh {% endcomment %}
<meta http-equiv="refresh" content="10">
{% endblock meta %}

{% block title %}
Results
{% endblock title %}

{% block content %}
<h1 class="my-4">Results</h1>

{% for job_name, dna_string, dna_result, state, progress, task_id in info %}
<!-- Blog Post -->
<div class="card mb-4">
  <div class="card-body">
    <h2 class="card-title">Job Name: {{ job_name }}</h2>
    <p class="card-text">DNA Sequence: {{ dna_string }}</p>
    <div class="progress">
      <div class="progress-bar" role="progressbar" style="width: {{ progress }}%" aria-valuenow="{{ progress }}"
        aria-valuemin="0" aria-valuemax="100">{{ state }}</div>
    </div>
    <p class="cart-text">{{ dna_result }}</p>
  </div>
  <div class="card-footer text-muted">
    <a class="btn btn-warning btn-sm mt-1 mb-1" href="{% url 'dnaStrings:cancel_job' task_id=task_id %}">Cancel</a>
    <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'dnaStrings:delete_job' task_id=task_id %}">Delete</a>
  </div>
</div>
{% endfor %}
{% endblock content %}

templates/submit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Submit
{% endblock title %}

{% block content %}
<h1 class="my-4">Submit A Job</h1>
<form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
        {{ form | crispy }}
    </fieldset>
    <div class="form-group">
        <button class="btn btn-primary" type="submit">Submit Job</button>
    </div>
</form>
<a href="{% url 'dnaStrings:monitor' %}"><button class="btn btn-info">Monitor Job</button></a>
{% endblock content %}